# Generated by Django 3.2.9 on 2021-11-03 03:57

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubCatgeory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=200)),
                ('selling_price', models.IntegerField(default=0)),
                ('cost_price', models.IntegerField(default=0)),
                ('on_discount', models.BooleanField(default=False)),
                ('avg_rating', models.CharField(default='', max_length=4)),
                ('no_of_review', models.IntegerField(default=0)),
                ('no_of_orders', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=20)),
                ('image1', models.ImageField(upload_to=app.models.Product.upload_image_to)),
                ('image2', models.ImageField(upload_to=app.models.Product.upload_image_to)),
                ('image3', models.ImageField(upload_to=app.models.Product.upload_image_to)),
                ('image4', models.ImageField(upload_to=app.models.Product.upload_image_to)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcatgeory')),
            ],
        ),
    ]
