# Generated by Django 3.2.9 on 2021-11-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='above',
            field=models.IntegerField(default=150),
        ),
    ]
