# Generated by Django 3.2.9 on 2021-11-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_couponcode_above'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_receipt', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=20)),
                ('razorpay_payment_id', models.CharField(max_length=20)),
                ('razorpay_order_id', models.CharField(max_length=20)),
                ('razorpay_signature', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=10)),
                ('subtotal', models.CharField(max_length=10)),
                ('products', models.TextField()),
                ('order_note', models.CharField(max_length=200)),
                ('shipping_charges', models.CharField(max_length=10)),
                ('couponname', models.CharField(blank=True, max_length=10, null=True)),
                ('discount', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
