# Generated by Django 3.2.9 on 2021-11-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211130_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(max_length=100),
        ),
    ]
