# Generated by Django 3.2.9 on 2022-02-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_razorpay_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_val',
            field=models.IntegerField(default=0),
        ),
    ]
